# # # # # # # #
#   K i k o   #
# # # # # # # #

# - markdown: kramdown

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

title: "Steve Giovannetti"
tagline: ""
description: "Follow <a href=\"https://micro.blog/gio\">@gio on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/gio\">@gio on Micro.blog</a>."
baseurl: ""
url: "http://microblog.stevegio.net"
markdown: "kramdown"
username: "gio"
microblog_user: "gio"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Steve Giovannetti"
name: "Steve Giovannetti"
gravatar_hash: "e299436bb7512f8a1163d959157e5bda"
avatar: "https://micro.blog/gio/avatar.jpg"
full_name: "Steve Giovannetti"
bio: ""
twitter_username: "stevegio"
github_username: "stevegio"
instagram_username: "stevegio"
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Michigan"
site_id: "390"
gems: ["jekyll-paginate"]
itunes_description: "Nerd from NJ. Proud dad. CTO of a security consultancy."
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Steve Giovannetti"
itunes_email: ""
podcast: false